### ISSUE TITLE
Dev | Summary page

### ISSUE THREAD

**Issue by ShaneHerath** [ShaneHerath/BrandSmacker#13]
1. Brand logo color needs to be blue
2. Well Done needs to change to "Thank You"
3. Please share the summary text needs to be big
4. Fix the alignment of the logo and Brandsmacker text
5. Share button and the brand contact checkbox on 2 lines

**Comment by brianperera** [comment]
Fixed the following
------------------------------
1. Brand logo color needs to be blue
2. Well Done needs to change to "Thank You"
 
Pending
-----------
3. Please share the summary text needs to be big
4. Fix the alignment of the logo and Brandsmacker text
5. Share button and the brand contact checkbox on 2 lines

**Comment by brianperera** [comment]
Fixed
------------
Please share the summary text needs to be big
Fix the alignment of the logo and Brandsmacker text
Share button and the brand contact checkbox on 2 lines

**Comment by brianperera** [comment]
Please test
