### ISSUE TITLE
Provide a KT to Sukitha on the attribute change

### ISSUE THREAD

**Issue by ShaneHerath** [ShaneHerath/BrandSmacker#17]

**Comment by brianperera** [comment]
Email sent to Sukitha with the details.

Delan has requested the following changes to be done on the slider default screens.

Attribute Sliders
1. The auto slide animation needs to happen from the right to the left.
2. The default/Neutral face will be a gray color one, not the yellow one. Taher will send us the new graphic for this.
3. The default text of the slider will state "Not Rated" 
4. Validations needs to be removed. The user needs to be able to proceed to the next screen without rating attributes.

Customer Satisfaction/Recommendation screen,
1. The default/Neutral face will be a gray color one, not the yellow one. Taher will send us the new graphic for this.
