### ISSUE TITLE
Attribute screen | default value changes

### ISSUE THREAD

**Issue by ShaneHerath** [ShaneHerath/BrandSmacker#2]
1. Default state will be a white face
2. Slide animation from right to left
3. Remove validations

**Comment by Kurama-X** [comment]
@brianperera 2nd and 3rd ones are completed and code checked in. 1st has a dependency on the images from @tahersajjad

**Comment by brianperera** [comment]
@Kurama-X the images have been integrated. 

Please test it and close this ticket

**Comment by Kurama-X** [comment]
Retested. This is fixed.
