### ISSUE TITLE
CR | Modifications to the attribute screen

### ISSUE THREAD

**Issue by brianperera** [ShaneHerath/BrandSmacker#26]
Enhancements
------------
When the attributes come up on each screen the thumb appears, then disappears. it should come across and stay there. can we make it flash like the unanswered attributes.

When swiping the attributes the name of the attribute comes up with a description of the score. It goes as soon as scored. can we introduce a slight time lag so it stays there, maybe for 1-2 seconds, then fades out. just a bit less sudden. 

The attribute name font and background is too similar to the question above it. can we have a background to it to differentiate it like the name of the score?

**Comment by brianperera** [comment]
@QCarru @delanbertinus @ShaneHerath @tahersajjad This is a change request that Q has suggested for the attribute screen. We will not be starting any development on this, until the requirement is discussed during the next meeting.

My suggestion is to do this post beta.

**Comment by ShaneHerath** [comment]
1. The scale will not go away, but only the thumb will go away and come back when you hover/rate the attribute.

2. As per Delan this will not be fixed.

3. Move the question a little bit to the top. Make the attribute name bold. Increase the gap between the question and the attribute name.

**Comment by brianperera** [comment]
All above are fixed
