### ISSUE TITLE
Create email address for support

### ISSUE THREAD

**Issue by ShaneHerath** [ShaneHerath/BrandSmacker#4]
1. Create support email address
2. Create info email

**Comment by ShaneHerath** [comment]
@brianperera @delanbertinus @QCarru Please confirm if below two email addresses will be okay?

support@brandsmacker.com
info@brandsmacker.com

**Comment by brianperera** [comment]
@ShaneHerath They are fine for me. I have added these to the FB app. Let know if they need to change. Otherwise you are good to close this issue @ShaneHerath

**Comment by ShaneHerath** [comment]
I'll get it done Brian.

Thanks
