### ISSUE TITLE
Dev | Industry screen

### ISSUE THREAD

**Issue by ShaneHerath** [ShaneHerath/BrandSmacker#7]
1. Big arrows
2. Align carousal with arrows
3. Fix the Scrolling issue - the image and the header does not match
4. Page heading needs a margin on top
5. Back arrow is not working

**Comment by Kurama-X** [comment]
- We need new big arrow images
- Removed scrolling but still if we click on next previous arrows quickly or drag quickly header  behavve abnormally

Rest is fixed

**Comment by brianperera** [comment]
@Kurama-X You are pushing the next command to a execution queue right? I think that is the problem. You need to push the header change to that queue alsojust after the next/previous command. That might fix it.

I will check-in the big arrow keys in a while

**Comment by brianperera** [comment]
@Kurama-X I have checked-in the next_large.png and previous_large.png files

**Comment by Kurama-X** [comment]
@brianperera Checked in all the changes except for the 3rd.

**Comment by Kurama-X** [comment]
Fixed these issues.
